### ISSUE TITLE
display sub menu in two columns. vertical sort order same as specified in shopify

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#1]
note: i re-sorted menu in Shopify to match their desired structure:

Shop all
Plates
Cups
Napkins
Straws
Cutlery
Table covers
Birthday candles + sparklers
Cake Toppers
Confetti
Balloons
Garlands + Banners

would be great if it appeared in two columns 
**left**: 
Shop all
Plates
Cups
Napkins
Straws
Cutlery
Table covers

**right**: 
Birthday candles + sparklers
Cake Toppers
Confetti
Balloons
Garlands + Banners

--
Plates
Cups
Napkins
Straws
Cutlery
Table covers

**Comment by lastant** [comment]
I implemented it as flex-direction:row with a wrap, so every second item is in the same column. I adjusted the menu accordingly, although the mobile menu has a difference sequence.

**Comment by pirco** [comment]
so there's no way to have them appear in the order they are entered in the menu defined in shopify, desktop and mobile?

or is it just too much work?

**Comment by lastant** [comment]
It should be possible, but then I'll need to specify at which height or at which item it's supposed to break to the second column.

**Comment by pirco** [comment]
Could you loop through the sub sub menus and split the array? Then display each in a column?

**Comment by lastant** [comment]
Ok, done

**Comment by pirco** [comment]
incoming request do make sure the left column is longer than the right, if uneven sub menu items

see https://thesocialsociety.com/collections/plates

<img width="607" alt="Screenshot 2024-10-03 at 16 18 20" src="https://github.com/user-attachments/assets/0114d04d-55a8-439c-bc8b-dd931964b4bc">

**Comment by lastant** [comment]
Ok, fixed it on the dev branch

**Comment by pirco** [comment]
thanks.
