### ISSUE TITLE
newsletter signup form

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#11]
likely not a fun project because we have to add a cookie to hide the signup form for, say, one year if someone clicks to close it OR  submits the form. plus, there's a very custom design. but let me know if you can do this.
on mobile, it should just have a rounded top, filling most of the screen with pink

**Comment by lastant** [comment]
Ok, added. But what is the form submission url?

**Comment by pirco** [comment]
hmm. does the Dawn theme not have a newsletter signup form? 
I should have mentioned that that should be used for this purpose...

sorry

**Comment by pirco** [comment]
but it looks beautiful. although it would be nice if you could match the close X button :)
and darken the rest of the site with an overlay?!

**Comment by lastant** [comment]
Ok, put the default form

**Comment by pirco** [comment]
reopening this with one question: can I trigger the signup form to pop up via hyperlink on any page even if the customer has clicked out of it (and cookie is set)? ?

**Comment by lastant** [comment]
I could add an action for a certain link href

**Comment by lastant** [comment]
You can open it with a code like this. It must have `<button>` inside.

`<modal-opener data-modal="#PopupModal-newsletter"><button>newsletter</button></modal-opener>`

**Comment by pirco** [comment]
brilliant
