### ISSUE TITLE
homepage product compilation not displaying images

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#12]
https://exkzb3mrspm2bedw-68428759265.shopifypreview.com
"Liquid error (sections/product-compilation line 13): invalid url input"

**Comment by lastant** [comment]
Investigated a lot, and found out these products were unpublished from the online store. It's the Publishing section on the product settings page.

**Comment by pirco** [comment]
damn. yea, I spent a little time on this as well. thanks for figuring it out.
