### ISSUE TITLE
about us page GSAP not defined

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#14]
sometimes, the scrolltrigger effect doesn't work on the about us page
<img width="1266" alt="Screenshot 2024-06-20 at 02 52 41" src="https://github.com/pirco/social-society-dawn/assets/146350/2413ff01-ff9f-449e-84d4-9d76701286a4">
(I made some CSS edits but that shouldn't affect that)

**Comment by pirco** [comment]
https://www.dropbox.com/s/ekuxsys28utuc29/socialsociety_aboutus_gsap_error.mov?dl=0

**Comment by lastant** [comment]
Ok fixed
