### ISSUE TITLE
media height fix for safari breaks object position

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#18]
after the change to the height attribute (to fix the hidden product images in safari) it is no longer possible to use object-position on other images. 

object-position: center center should center images vertically and horizontally

there must be another fix to showing product card images in safari – other than changing the core CSS attribute for .media since that affects every image on the site. 

https://www.dropbox.com/scl/fi/76j425dmklqdoj4q5nq51/social_society_media_object_position.mov?rlkey=0z7rbiz6vp7xoi47xkj9ar5om&dl=0

**Comment by lastant** [comment]
Ok I made it to only apply to safari browsers.

**Comment by pirco** [comment]
but the problem is that safari now doesn't object-position images properly!
we can't ignore safari here. more importantly, this isn't an issue with the default Dawn theme

can you try and figure out what made this break?

<img width="469" alt="Screenshot 2024-08-22 at 16 21 11" src="https://github.com/user-attachments/assets/8a3a841f-2d3f-4cfa-ae20-4ef15b12a7a2">

**Comment by lastant** [comment]
I'll have a look again later today, but actually the original dawn theme as you showed uses auto, and that's what i use for safari. Does dawn have object position center?

**Comment by pirco** [comment]
Dawn seems to use height: 100%. and yes. they do object position center.

<img width="1394" alt="Screenshot 2024-08-22 at 17 02 41" src="https://github.com/user-attachments/assets/1c7299e5-8d76-4d2f-8fc4-3bcba4ffda2b">
