### ISSUE TITLE
make teaser section on PDP dynamic

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#2]
the "every day is a reason to celebrate" section will be different for some products if not most.

typically, I would do this with metafields so that any product can overwrite the default headline/text/photo/graphic/link

thoughts?

**Comment by lastant** [comment]
Implemented, see example here: /products/16-inch-ombre-orbz-blue-and-green-foil-balloon

**Comment by pirco** [comment]
great. 

FYI, i had added some custom metafields myself as you probably saw.
