### ISSUE TITLE
start ABOUT US page

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#3]
for ABOUT US 
can you create a new and separate custom "image + text" section please?
custom fields should be clear per figma: 
subtitle, headline, image, section title, WYSIWYG text
I suppose the icons could be pre-defined , just let them select the one to highlight 

please note the custom CHECK OUR INSTA teaser header at the bottom of the page

**Comment by lastant** [comment]
But on figma comment it says it should scroll like https://meau.co/pages/about  Then it should probably be one section with blocks for each subsection, and using scrolltrigger etc

**Comment by pirco** [comment]
oh, you're right. I didn't see that comment. 
ok then. just make sure to check the mobile behaviour: regular scroll, but images zoom in as you scroll.

**Comment by pirco** [comment]
let me know if you can make progress on this. thanks.

**Comment by lastant** [comment]
Ok, I've also added the scrolltrigger. But I'm not sure what it should do on the mobile.

**Comment by pirco** [comment]
You can do the same as the sample she sent meau.co

**Comment by lastant** [comment]
Ok, also adjusted for the mobile. Just made it scroll normally with intermittent blocks.
