### ISSUE TITLE
start IN-STORE EVENTS 

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#5]
per figma,

should be a separate blog with listing and event detail
if you can set up a separate contact form that links from the RSVP button, would be great

and make sure the event title gets submitted along side the user-entered info 
(there's no layout for the RSVP form but perhaps you can use a lightbox/modal to display a simple form.

**Comment by lastant** [comment]
Ok, implemented here: https://thesocialsociety.com/blogs/in-store-events-5

**Comment by lastant** [comment]
To create additional forms, it seems we need an app like this? https://apps.shopify.com/shopify-forms?st_campaign=admin-search&st_source=admin&utm_campaign=admin-search&utm_source=admin

**Comment by pirco** [comment]
hmm I don't think we need an app just yet. if you will, just set up another regular contact us form (https://shopify.dev/docs/storefronts/themes/customer-engagement/add-contact-form) with a different subject line.

if need be, they'll have to route emails on their end via rules in their mail app/service.  or we look into an app at that point.

**Comment by pirco** [comment]
btw, the In Store events look great. thank you. 
two quick updates: can you remove the featured image from the article template? it's just too large. 
I'll tell them to embed the image into the blog post and use a landscape format. 

also, FYI, I changed the slug of the blog and connected to the secondary nav system

**Comment by lastant** [comment]
Updated the single event page, also added the rsvp form and sent a test rsvp.

**Comment by pirco** [comment]
that's great. anyway we can present a "thank you for your RSVP" in the popup when someone submits? 
also, make sure to mention "test" somewhere in the form when you submit a RSVP for testing. thanks
oh and please have the event detail page read "back to events" at the bottom.

**Comment by lastant** [comment]
I've setup a redirect to this page: https://thesocialsociety.com/pages/thank-you
