### ISSUE TITLE
homepage hover effect Best Sellers

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#6]
Can you check why the 12” sparklers don’t have that effect? 

I see the actual clip-path for the bag icon on line 424 in themes.liquid
And line 425 in custom.css has the right definition

But hovering over the sparklers on the site doesn’t show an effect.

**Comment by lastant** [comment]
Ok, fixed

**Comment by pirco** [comment]
well, I must have hovered a hundred times but I think it really only works when you move your mouse very slowly. as much as I like the hover animation, it doesn't work reliably. can we try without animation? can you test to make sure it always works?
if not, we might just have to nix the hover idea and display those shapes by default.

**Comment by pirco** [comment]
https://www.dropbox.com/scl/fi/od50qi6n2xbkhmgkr67yw/social_society_svg_clippath_hover_effect.mov?rlkey=l8ccmnjxf6aqgkic7vyun2dxj&dl=0

**Comment by lastant** [comment]
I think now it's fixed, also made it a bit faster.

**Comment by pirco** [comment]
this. is awesome!

**Comment by pirco** [comment]
can you tell me again where to specify the SVG paths for the hover clip effect? you mentioned " The shape is determined by the collection the product belongs to. It's defined in custom.css "
 but I can't find it :-(

**Comment by lastant** [comment]
It's in https://github.com/pirco/social-society-dawn/blob/main/snippets/card-product.liquid
