### ISSUE TITLE
PDP 'you may also like" section

### ISSUE THREAD

**Issue by pirco** [pirco/social-society-dawn#7]
please update 

<img width="1460" alt="Screenshot 2024-06-10 at 09 23 35" src="https://github.com/pirco/social-society-dawn/assets/146350/59b9f7a3-b9ec-4202-ab3d-3d0f70848654">

to look like this

<img width="892" alt="Screenshot 2024-06-10 at 09 22 49" src="https://github.com/pirco/social-society-dawn/assets/146350/2d9c260d-ff70-4440-bf78-7833dcefbd83">

please check lines and spacing as well.

**Comment by pirco** [comment]
perhaps you can add the current product's first collection title below the SHOP THIS PARTY

**Comment by lastant** [comment]
Ok, added the heading

**Comment by lastant** [comment]
Ok, added the heading
